// Auto-generated by `supabase gen types typescript`.
// Run `pnpm --filter @squarely/db gen-types` after schema changes.
// Placeholder until first migration is run.
export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export type Database = {
  public: {
    Tables: Record<string, never>;
    Views: Record<string, never>;
    Functions: Record<string, never>;
    Enums: Record<string, never>;
    CompositeTypes: Record<string, never>;
  };
};
